### ISSUE TITLE
react-ladda from npm outdated

### ISSUE THREAD

**Issue by TGMorais** [jsdir/react-ladda#24]
Hi, 

I just installed react-ladda from npm `npm install --save react-ladda`, and I notice the code is outdated when compared to the repo.

This the code  of `componentDidUpdate` inside `node_modules/react-ladda/index.js`

```javascript
componentDidUpdate: function() {
    if (!this.laddaButton) {
      return;
    }

    // Skip if the button was initially disabled.
    if (!this.props.loading && this.props.disabled) {
      return;
    }

    if (this.props.loading && !this.laddaButton.isLoading()) {
      this.laddaButton.start();
    } else if (!this.props.loading && this.laddaButton.isLoading()){
      this.laddaButton.stop();
    }

    if (typeof this.props.progress !== 'undefined') {
      this.laddaButton.setProgress(this.props.progress);
    }
  }
```

It seems the latest commit (29897875a575d355de0e6fca455ff33885da26e0) is not on npm, which is a same since it fixed the problem I'm having.

**Comment by jsdir** [comment]
Thanks for noticing. I've just published the latest changes in `react-ladda@4.0.1`.

**Comment by TGMorais** [comment]
Thanks! :+1:

**Comment by antoniopuero** [comment]
Hm, I've faced the same issue with 4.0.3. The code on the npm is still the same as in 4.0.1 version

**Comment by jsdir** [comment]
@antoniopuero this should be fixed in `react-ladda@4.0.4`
